# Si quieres, puedes borrar la línea 'version: 3.8' para quitar la advertencia
services:
  api:
    build: .
    depends_on:
      - db
    ports:
      - "3000:3000"
    # ¡ESTA ES LA LÍNEA CLAVE QUE FALTABA!
    # Le ordena a Docker Compose que cargue el archivo .env en este contenedor
    env_file:
      - ./.env

  db:
    image: postgres:14
    ports:
      - "5432:5432"
    environment:
      # Leemos las variables desde el archivo .env
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE}
    # volumes:
    #   - ./postgres-data:/var/lib/postgresql/data